console.log("this is a new file ");
console.log("object");
console.log("Xin chào mọi người ");
console.log("Hello");
console.log("abcbcbcbcbbc");
console.log("hfjhfkjsdhfksd");
console.log("jsdhfkjsdhfksd");
console.log("ndbfksdfdh");
console.log("ndnfjsdnfds");
console.log("njfsdkjfhsd");
